//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIProjectDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class account
    {
        public int acc_id { get; set; }
        public Nullable<int> emp_id { get; set; }
        public string acc_username { get; set; }
        public string acc_password { get; set; }
        public Nullable<int> role_id { get; set; }
    }
}
