//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIProjectDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int emp_id { get; set; }
        public string emp_name { get; set; }
        public string emp_position { get; set; }
        public Nullable<System.DateTime> emp_dob { get; set; }
        public string emp_contact_number { get; set; }
    }
}
